#!/usr/bin/env bash
# One-command setup: generates secrets, writes .env, starts the stack.
# Idempotent: with an existing .env it just (re)starts the stack.
# Re-configure from scratch: rm .env && ./setup.sh
set -euo pipefail

info() { printf '\033[0;34m▸ %s\033[0m\n' "$*"; }
success() { printf '\033[0;32m✔ %s\033[0m\n' "$*"; }
fail() { printf '\033[0;31m✖ %s\033[0m\n' "$*" >&2; exit 1; }

cd "$(dirname "$0")"

command -v docker >/dev/null || fail "docker is required (https://get.docker.com)"
docker compose version >/dev/null 2>&1 || fail "docker compose v2 is required"

PUBLIC_BASE_URL="${PUBLIC_BASE_URL:-http://localhost:3000}"

if [ -f .env ]; then
  info "existing .env found — starting the stack"
else
  info "generating secrets and writing .env"
  POSTGRES_PASSWORD=$(openssl rand -hex 16)
  AUTH_SECRET=$(openssl rand -hex 32)
  SETUP_TOKEN=$(openssl rand -hex 16)
  METRICS_TOKEN=$(openssl rand -hex 16)
  cat > .env <<EOF
# Auto-generated by setup.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# To reconfigure: rm .env && ./setup.sh
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
AUTH_SECRET=${AUTH_SECRET}
SETUP_TOKEN=${SETUP_TOKEN}
METRICS_TOKEN=${METRICS_TOKEN}
PUBLIC_BASE_URL=${PUBLIC_BASE_URL}
EOF
  chmod 600 .env
  success ".env written (mode 600)"
fi

info "pulling images and starting"
docker compose up -d --pull always --wait --wait-timeout 180

# shellcheck disable=SC1091
source ./.env
success "stack is up"
echo
echo "  Dashboard:    ${PUBLIC_BASE_URL}"
echo "  First boot:   open the dashboard and complete the setup wizard."
echo "  Setup token:  ${SETUP_TOKEN:-<none>}   (required by the wizard; keep it private)"
echo
echo "  Health:       curl ${PUBLIC_BASE_URL}/healthz"
echo "  Update:       ./update.sh"
echo "  Backup:       ./scripts/backup.sh"
